myname: Asmir Mustafic
twitter: goetas_asmir
repo: https://github.com/goetas/www.goetas.com
github: goetas
linkedin: goetas
google_analytics_tracking_id: UA-52602579-2
# note: stash this when working locally
url: http://www.goetas.com
