sculpin_content_types:
  posts:
    permalink: blog/:title/
    taxonomies:
        - tags
        - categories
  projects:
    permalink: project/:slug_title/
    taxonomies:
        - tags
        - categories
